=== KiriBogach/arso/xml_soluciones/ejercicio1.2/ejercicio2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT calificaciones (calificacion+, diligencia*)>
 
<!ATTLIST calificaciones asignatura NMTOKEN #REQUIRED
                     	convocatoria (febrero|junio|julio) #REQUIRED
                     	curso NMTOKEN #IMPLIED>
 
<!ELEMENT calificacion (nif, nombre?, nota)>
 
<!ELEMENT nif (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nota (#PCDATA)>
 
<!ELEMENT diligencia (nif, nombre?, nota)>
 
<!ATTLIST diligencia fecha CDATA #REQUIRED
                 	extraordinaria (si|no) "no">

=== KiriBogach/arso/xml_soluciones/ejercicio1.2/ejercicio2.xml
<?xml version="1.0" ?>

<!DOCTYPE calificaciones SYSTEM "ejercicio2.dtd">

<calificaciones convocatoria="febrero" curso="2017" asignatura="1902">
  	<calificacion>
        	<nif>23322156M</nif>
        	<nota>10</nota>
  	</calificacion>  
  	<calificacion>
        	<nif>13322156M</nif>
        	<nombre>Pepe</nombre>  
        	<nota>8</nota>
  	</calificacion>  
  	<diligencia fecha="2019-02-05">
        	<nif>13322156M</nif>
        	<nota>9</nota>	
  	</diligencia>
</calificaciones>
