=== KiriBogach/arso/arso-Bogach-Kyryl/xml/ejercicio1/ejercicio1.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT libro (titulo, autor, seccion+)>
 
<!ELEMENT titulo (#PCDATA)>
 
<!ELEMENT autor (#PCDATA)>
 
<!ELEMENT seccion (nombre, contenido?)>
 
<!ELEMENT nombre (#PCDATA)>
 
<!ELEMENT contenido (texto | seccion+)>
 
<!ELEMENT texto (#PCDATA)>

=== KiriBogach/arso/arso-Bogach-Kyryl/xml/ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE poema SYSTEM "ejercicio1.dtd">

<libro>
   	<titulo>El Teclado</titulo>
   	<autor>Eduardo Santos</autor>
   	<seccion>
         	<nombre>Introduccion</nombre>
         	<contenido>
                	<texto>Esta es la Introduccion</texto>
         	</contenido>
   	</seccion>
   	<seccion>
         	<nombre>Primer tomo</nombre>
         	<contenido>
                	<seccion>
                      	<nombre>S1</nombre>
                	</seccion>
                	<seccion>
                      	<nombre>S2</nombre>
                	</seccion>
         	</contenido>
   	</seccion>
</libro>
