=== KiriBogach/arso/xml/ejercicio2-bookle/bookle.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Bien -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/bookle"
	xmlns:tns="http://www.example.org/bookle"
	elementFormDefault="qualified">

	<!-- Elemento raÃ­z: -->
	<xs:element name="actividad" type="tns:tipo_actividad" />

	<!-- Tipos: -->
	<xs:complexType name="tipo_actividad">
		<xs:sequence>
			<xs:element name="titulo" type="xs:string" />
			<xs:element name="descripcion" type="xs:string"
				minOccurs="0" />
			<xs:element name="profesor" type="xs:string" />
			<xs:element name="email" type="tns:tipo_email"
				minOccurs="0" />
			<xs:element name="agendas" type="tns:tipo_agendas" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:unsignedLong"
			use="required" />
	</xs:complexType>

	<xs:complexType name="tipo_agendas">
		<xs:sequence>
			<xs:element name="agenda" type="tns:tipo_agenda"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipo_agenda">
		<xs:sequence>
			<xs:element name="fecha" type="xs:date" />
			<xs:element name="turnos" type="tns:tipo_turnos" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipo_turnos">
		<xs:sequence>
			<xs:element name="turno" type="tns:tipo_turno"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipo_turno">
		<xs:sequence>
			<xs:element name="horario" type="xs:string" />
			<xs:element name="reserva" type="tns:tipo_reserva"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipo_reserva">
		<xs:sequence>
			<xs:element name="alumno" type="xs:string" />
			<xs:element name="email" type="tns:tipo_email"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:unsignedLong"
			use="required" />
	</xs:complexType>

	<xs:simpleType name="tipo_email">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== KiriBogach/arso/xml/ejercicio2-bookle/bookle.xml
<?xml version="1.0" encoding="UTF-8"?>

<actividad id="5"
	xmlns="http://www.example.org/bookle"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/bookle bookle.xsd ">
	
	<titulo>Entrevista Prácticas ArSo</titulo>
	<descripcion>[OPCIONAL] Evaluamos la práctica</descripcion>
	<profesor>Marcos Senpai</profesor>
	<email>[OPCIONAL] marcos@um.es</email>
	<agendas>
		<agenda>
			<fecha>2018-02-26</fecha>
			<turnos>
				<turno>
					<horario>9:00 - 10:00</horario>
					<reserva id="10">
						<alumno>Kyryl Bogach</alumno>
						<email>[OPCIONAL] k.bogach@gmail.com</email>
					</reserva>
				</turno>
				<turno>
					<horario>10:00 - 11:00</horario>
				</turno>
			</turnos>
		</agenda>
		<agenda>
			<fecha>2018-02-27</fecha>
			<turnos>
				<turno>
					<horario>10:30 - 11:30</horario>
					<reserva id="17">
						<alumno>Joaquín Brotons</alumno>
					</reserva>
				</turno>
			</turnos>
		</agenda>
	</agendas>
</actividad>
