=== KiriBogach/arso/xml/ejercicio1.3/ejercicio3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/calificaciones"
	xmlns:tns="http://www.example.org/calificaciones" elementFormDefault="qualified">

	<!-- Tipos: -->
	<complexType name="tipo_calificaciones">
		<sequence>
			<element name="asignatura" type="string" />
			<element name="calificacion" type="tns:tipo_calificacion"
				maxOccurs="unbounded" />
			<element name="diligencia" type="tns:tipo_diligencia"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="curso" type="positiveInteger" use="optional" />
		<attribute name="convocatoria" type="tns:tipo_convocatoria"
			use="required" />
	</complexType>

	<simpleType name="tipo_convocatoria">
		<restriction base="string">
			<enumeration value="febrero" />
			<enumeration value="junio" />
			<enumeration value="julio" />
		</restriction>
	</simpleType>

	<complexType name="tipo_calificacion">
		<sequence>
			<element name="nif" type="string" />
			<element name="nombre" type="string" minOccurs="0" />
			<element name="nota" type="tns:tipo_nota" />
		</sequence>
	</complexType>

	<complexType name="tipo_diligencia">
		<complexContent>
			<extension base="tns:tipo_calificacion">
				<sequence>
					<element name="fecha" type="date" />
				</sequence>
				<attribute name="extraordinaria" type="string" default="no" />
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="tipo_nota">
		<restriction base="double">
			<minInclusive value="0" />
			<maxInclusive value="10" />
		</restriction>
	</simpleType>
	
	<!-- Elemento raÃ­z: -->
	<element name="calificaciones" type="tns:tipo_calificaciones" />
</schema>

=== KiriBogach/arso/xml/ejercicio1.3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>

<calificaciones convocatoria="junio" curso="2019"
	xmlns="http://www.example.org/calificaciones" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/calificaciones ejercicio3.xsd ">

	<asignatura>ArSo</asignatura>
	<calificacion>
		<nif>X5126520G</nif>
		<nombre>Kyryl Bogach</nombre>
		<nota>9.1</nota>
	</calificacion>
	<calificacion>
		<nif>48215212F</nif>
		<nombre>Antonio Garcia</nombre>
		<nota>5.715</nota>
	</calificacion>

	<diligencia extraordinaria="si">
		<nif>57292512F</nif>
		<nombre>Pedro Ferrandez</nombre>
		<nota>9.52</nota>
		<fecha>2019-07-26</fecha>
	</diligencia>
	
</calificaciones>

=== KiriBogach/arso/arso-Bogach-Kyryl/xml/ejercicio3/calificaciones-modificado.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><calificaciones xmlns="http://www.example.org/calificaciones" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" convocatoria="junio" curso="2019" xsi:schemaLocation="http://www.example.org/calificaciones ejercicio3.xsd ">

	<asignatura>ArSo</asignatura>
	<calificacion>
		<nif>75126520G</nif>
		<nombre>Kyryl Bogach</nombre>
		<nota>9.6</nota>
	</calificacion>
	<calificacion>
		<nif>48215212F</nif>
		<nombre>Antonio Garcia</nombre>
		<nota>6.215</nota>
	</calificacion>

	<diligencia extraordinaria="si">
		<nif>57292512F</nif>
		<nombre>Pedro Ferrandez</nombre>
		<nota>10.0</nota>
		<fecha>2019-02-13</fecha>
	</diligencia>
	
	<diligencia>
		<nif>87292512F</nif>
		<nota>2.3</nota>
		<fecha>2019-07-26</fecha>
	</diligencia>
	
	<diligencia extraordinaria="si">
		<nif>67292512F</nif>
		<nota>1.0</nota>
		<fecha>2019-07-26</fecha>
	</diligencia>
	
</calificaciones>
