=== KiriBogach/arso/xml/ejercicio-bookle/bookle.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bookle (actividades)>
<!ELEMENT actividades (actividad*)>
<!ELEMENT actividad (titulo, descripcion?, profesor, email?, agendas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT agendas (agenda+)>
<!ELEMENT agenda (fecha, turnos)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT turnos (turno+)>
<!ELEMENT turno (horario, reserva?)>
<!ELEMENT horario (#PCDATA)>
<!ELEMENT reserva (alumno, email?)>
<!ELEMENT alumno (#PCDATA)>

<!ATTLIST actividad 
	id CDATA #REQUIRED>
<!ATTLIST reserva 
	id CDATA #REQUIRED>

=== KiriBogach/arso/xml/ejercicio-bookle/bookle.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE poema SYSTEM "bookle.dtd">

<actividad id="5">
	<titulo>Entrevista Prácticas ArSo</titulo>
	<descripcion>[OPCIONAL] Evaluamos la práctica</descripcion>
	<profesor>Marcos Senpai</profesor>
	<email>[OPCIONAL] marcos@um.es</email>
	<agendas>
		<agenda>
			<fecha>2018-02-26</fecha>
			<turnos>
				<turno>
					<horario>9:00 - 10:00</horario>
					<reserva id="10">
						<alumno>Kyryl Bogach</alumno>
						<email>[OPCIONAL] k.bogach@gmail.com</email>
					</reserva>
				</turno>
				<turno>
					<horario>10:00 - 11:00</horario>
				</turno>
			</turnos>
		</agenda>
		<agenda>
			<fecha>2018-02-27</fecha>
			<turnos>
				<turno>
					<horario>10:30 - 11:30</horario>
					<reserva id="17">
						<alumno>Joaquín Brotons</alumno>
					</reserva>
				</turno>
			</turnos>
		</agenda>
	</agendas>
</actividad>
